### ISSUE TITLE
Doesn't work with RubyMotion

### ISSUE THREAD

**Issue by qrush** [zachwaugh/ZWEmoji#2]
This looks like the new NSDictionary syntax...

``` ruby
lib/ZWEmoji.m:68:12: error: unexpected '@' in program
    return @{@"string" : string};
           ^
lib/ZWEmoji.m:91:10: error: unexpected '@' in program
  return @{@"string" : emojiString, @"emojis" : emojiReplaced};
         ^
lib/ZWEmoji.m:96:11: error: unexpected '@' in program
        _codes = @{
```

**Comment by qrush** [comment]
I tried to convert these to the old syntax and had a bear of a time. :(

**Comment by zachwaugh** [comment]
Just reverted to the old NSDictionary syntax in 2b43a015964591fcd328ca0e914be66c0f392d84, try it now, and see if that works better. Probably better for the core library to use the most compatible syntax anyway.

**Comment by qrush** [comment]
Yeah, still doesn't work...I'm getting a lot of strange errors. Here's how to reproduce:

```
motion create EmojiTest
cd EmojiTest
mkdir vendor
git clone https://github.com/zachwaugh/ZWEmoji vendor/ZWEmoji
```

Edit the `Rakefile` to include:

```
  app.vendor_project "vendor/ZWEmoji/lib", :static
```

Then run `rake`, and:

```
(main)> ZWEmoji.emojiForCode(":1:")
2012-09-06 16:08:29.259 EmojiTest[33657:f803] -[__NSCFData objectForKey:]: unrecognized selector sent to instance 0xe05bd00
2012-09-06 16:08:29.261 EmojiTest[33657:f803] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFData objectForKey:]: unrecognized selector sent to instance 0xe05bd00'
*** First throw call stack:
(0x165b022 0x23fcd6 0x165ccbd 0x15c1ed0 0x15c1cb2 0x30ee 0xed6f867 0xeb5bc 0xed6f46a 0xed6f7c3 0xe3cdfa2 0x25b28d9 0x25b3509 0x1592803 0x1591d84 0x1591c9b 0x26337d8 0x263388a 0x577626 0xf690 0xf465)
terminate called throwing an exceptionrake aborted!
Command failed with status (1): [DYLD_FRAMEWORK_PATH="/Applications/Xcode.a...]
```

The `ZWEmoji` constant is there though...so it is compiling.

**Comment by zachwaugh** [comment]
Hmm, I've never used RubyMotion, and didn't buy it so I can't test that. I'm using ARC, so I'm wondering if that is the issue. I just pushed another update that should make it work whether it's using ARC or not, so try 75b0869e20aa8af6ff108d26ecef891453a4c873.

**Comment by qrush** [comment]
That did the trick! Thanks dude!

**Comment by zachwaugh** [comment]
Awesome, love to hear what you use it for. Let me know if you find any bugs.
